name = "AddInit"
uuid = "fb98f0d0-f82c-4729-879a-95be0d8634ee"
authors = ["bowaer <cb229435444@outlook.com> and contributors"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
